name: CI for Development

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring, pdo, sqlite3, bcmath, fileinfo, openssl, tokenizer, xml, ctype, json, curl, zip
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            dependencies-composer-

      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Create .env file
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Create SQLite Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run Database Migrations
        run: php artisan migrate --force
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite

      - name: Run Tests
        run: ./vendor/bin/pest --parallel
        env:
          APP_ENV: testing
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"

      - name: Run Laravel Pint (Code Style)
        run: ./vendor/bin/pint --test

      - name: Run PHPUnit with Coverage (if needed)
        run: php artisan test --coverage
        if: false # Enable this if you want coverage reports
